push test

diff --git a/.github/workflows/deploy-reusable.yml b/.github/workflows/deploy-reusable.yml
--- a/.github/workflows/deploy-reusable.yml
+++ b/.github/workflows/deploy-reusable.yml
@@ -4,184 +4,188 @@ permissions:
   id-token: write
   contents: read
 
-on:
-  workflow_call:
-    inputs:
-      module:
-        required: true
-        type: string
-      dockerfile_path:
-        required: true
-        type: string
-      compose_service:
-        required: true
-        type: string
-    secrets:
-      ENV_IMAGE_NAME:
-        required: true
-      MYSQL_DATABASE:
-        required: true
-      MYSQL_HOST:
-        required: true
-      MYSQL_PASSWORD:
-        required: true
-      MYSQL_PORT:
-        required: true
-      MYSQL_USERNAME:
-        required: true
-      SPRING_DATABASE_URL:
-        required: true
-      ECR_REGISTRY:
-        required: true
-      AWS_REGION:
-        required: true
-      AWS_ROLE_TO_ASSUME:
-        required: true
-      EC2_PUBLIC_IP:
-        required: true
-      EC2_USERNAME:
-        required: true
-      EC2_SSH_KEY:
-        required: true
-      S3_BUCKET_NAME:
-        required: true
-      S3_REGION:
-        required: true
-      S3_ACCESS_KEY:
-        required: true
-      S3_SECRET_KEY:
-        required: true
-      JWT_SECRET:
-        required: true
-      GOOGLE_CLIENT_ID:
-        required: true
-      GOOGLE_CLIENT_SECRET:
-        required: true
-      GOOGLE_REDIRECT_URI:
-        required: true
-  workflow_dispatch:
+
+#on:
+#  workflow_call:
+#    inputs:
+#      module:
+#        required: true
+#        type: string
+#      dockerfile_path:
+#        required: true
+#        type: string
+#      compose_service:
+#        required: true
+#        type: string
+#    secrets:
+#      ENV_IMAGE_NAME:
+#        required: true
+#      MYSQL_DATABASE:
+#        required: true
+#      MYSQL_HOST:
+#        required: true
+#      MYSQL_PASSWORD:
+#        required: true
+#      MYSQL_PORT:
+#        required: true
+#      MYSQL_USERNAME:
+#        required: true
+#      SPRING_DATABASE_URL:
+#        required: true
+#      ECR_REGISTRY:
+#        required: true
+#      AWS_REGION:
+#        required: true
+#      AWS_ROLE_TO_ASSUME:
+#        required: true
+#      EC2_PUBLIC_IP:
+#        required: true
+#      EC2_USERNAME:
+#        required: true
+#      EC2_SSH_KEY:
+#        required: true
+#      S3_BUCKET_NAME:
+#        required: true
+#      S3_REGION:
+#        required: true
+#      S3_ACCESS_KEY:
+#        required: true
+#      S3_SECRET_KEY:
+#        required: true
+#      JWT_SECRET:
+#        required: true
+#      GOOGLE_CLIENT_ID:
+#        required: true
+#      GOOGLE_CLIENT_SECRET:
+#        required: true
+#      GOOGLE_REDIRECT_URI:
+#        required: true
+#  workflow_dispatch:
 
 jobs:
   build:
     name: 🛠 Build & Push Docker Image
     runs-on: ubuntu-latest
-    outputs:
-      timestamp-tag: ${{ steps.generate-tag.outputs.timestamp-tag }}
+#    outputs:
+#      timestamp-tag: ${{ steps.generate-tag.outputs.timestamp-tag }}
     steps:
-      - uses: actions/checkout@v4
-
-      - name: Generate timestamp tag
-        id: generate-tag
-        run: |
-          TIMESTAMP_TAG=$(date +%y%m%d_T%H)
-          echo "timestamp-tag=$TIMESTAMP_TAG" >> $GITHUB_OUTPUT
-          echo "Generated timestamp tag: $TIMESTAMP_TAG"
-
-      - name: Gradle Build
-        run: ./gradlew :${{ inputs.module }}:bootJar -x test
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-          aws-region: ${{ secrets.AWS_REGION }}
-
-      - name: Login to Amazon ECR
-        uses: aws-actions/amazon-ecr-login@v2
-
-      - name: Create ECR repo if missing
-        run: |
-          aws ecr describe-repositories --repository-names ${{ inputs.module }} || \
-          aws ecr create-repository --repository-name ${{ inputs.module }}
-
-      - name: Build and Push Docker image (Multi-Architecture)
-        run: |
-          docker buildx build \
-            --platform linux/amd64,linux/arm64 \
-            --push \
-            -t ${{ secrets.ECR_REGISTRY }}/${{ inputs.module }}:latest \
-            -t ${{ secrets.ECR_REGISTRY }}/${{ inputs.module }}:${{ steps.generate-tag.outputs.timestamp-tag }} \
-            -f ${{ inputs.dockerfile_path }} \
-            ./${{ inputs.module }}
-
-  deploy:
-    name: 🚀 Deploy to EC2
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Clear EC2 server folder
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.EC2_PUBLIC_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            sudo rm -rf ~/apps/server
-            mkdir -p ~/apps/server
-            sudo chown -R $USER:$USER ~/apps/server
-
-      - name: Copy docker-compose.yml
-        uses: appleboy/scp-action@v0.1.4
-        with:
-          host: ${{ secrets.EC2_PUBLIC_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          source: "docker-compose.yml"
-          target: ~/apps/server
-
-      - name: Restart container
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.EC2_PUBLIC_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            cd ~/apps/server
-            cat <<EOF > .env
-            SPRING_PROFILES_ACTIVE=prod
-            IMAGE_NAME=${{ secrets.ENV_IMAGE_NAME }}
-            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
-            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
-            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
-            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
-            MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
-            SPRING_DATABASE_URL=${{ secrets.SPRING_DATABASE_URL }}
-            ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}
-            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
-            S3_REGION=${{ secrets.S3_REGION }}
-            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
-            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
-            JWT_SECRET=${{ secrets.JWT_SECRET }}
-            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
-            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
-            GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
-            EOF
-
-            echo "[Disk] Before cleanup"
-            df -h /
-
-            docker container prune -f
-            docker image prune -f
-            #docker network prune -f
-
-            # shared-net 네트워크 생성 (없는 경우에만)
-            docker network ls | grep shared-net || docker network create shared-net
-
-            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
-              | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
-
-            docker pull ${{ secrets.ECR_REGISTRY }}/${{ inputs.module }}:latest
-
-            docker compose down ${{ inputs.compose_service }}
-            docker compose up -d ${{ inputs.compose_service }}
-
-            echo "=== Container Status ==="
-            docker ps -a || true
-
-            echo "=== Logs (${{ inputs.compose_service }}) ==="
-            docker compose logs ${{ inputs.compose_service }} || true
+      - name: Test_Yaml
+        run :
+          echo ${{ secrets.AWS_ROLE_TO_ASSUME }}
+#      - uses: actions/checkout@v4
+#
+#      - name: Generate timestamp tag
+#        id: generate-tag
+#        run: |
+#          TIMESTAMP_TAG=$(date +%y%m%dT%H%M)
+#          echo "timestamp-tag=$TIMESTAMP_TAG" >> $GITHUB_OUTPUT
+#          echo "Generated timestamp tag: $TIMESTAMP_TAG"
+#
+#      - name: Gradle Build
+#        run: ./gradlew :${{ inputs.module }}:bootJar -x test
+#
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v3
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v4
+#        with:
+#          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+#          aws-region: ${{ secrets.AWS_REGION }}
+#
+#      - name: Login to Amazon ECR
+#        uses: aws-actions/amazon-ecr-login@v2
+#
+#      - name: Create ECR repo if missing
+#        run: |
+#          aws ecr describe-repositories --repository-names ${{ inputs.module }} || \
+#          aws ecr create-repository --repository-name ${{ inputs.module }}
+#
+#      - name: Build and Push Docker image (Multi-Architecture)
+#        run: |
+#          docker buildx build \
+#            --platform linux/amd64,linux/arm64 \
+#            --push \
+#            -t ${{ secrets.ECR_REGISTRY }}/${{ inputs.module }}:latest \
+#            -t ${{ secrets.ECR_REGISTRY }}/${{ inputs.module }}:${{ steps.generate-tag.outputs.timestamp-tag }} \
+#            -f ${{ inputs.dockerfile_path }} \
+#            ./${{ inputs.module }}
+#
+#  deploy:
+#    name: 🚀 Deploy to EC2
+#    runs-on: ubuntu-latest
+#    needs: build
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Clear EC2 server folder
+#        uses: appleboy/ssh-action@v0.1.6
+#        with:
+#          host: ${{ secrets.EC2_PUBLIC_IP }}
+#          username: ${{ secrets.EC2_USERNAME }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script: |
+#            sudo rm -rf ~/apps/server
+#            mkdir -p ~/apps/server
+#            sudo chown -R $USER:$USER ~/apps/server
+#
+#      - name: Copy docker-compose.yml
+#        uses: appleboy/scp-action@v0.1.4
+#        with:
+#          host: ${{ secrets.EC2_PUBLIC_IP }}
+#          username: ${{ secrets.EC2_USERNAME }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          source: "docker-compose.yml"
+#          target: ~/apps/server
+#
+#      - name: Restart container
+#        uses: appleboy/ssh-action@v0.1.6
+#        with:
+#          host: ${{ secrets.EC2_PUBLIC_IP }}
+#          username: ${{ secrets.EC2_USERNAME }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script: |
+#            cd ~/apps/server
+#            cat <<EOF > .env
+#            SPRING_PROFILES_ACTIVE=prod
+#            IMAGE_NAME=${{ secrets.ENV_IMAGE_NAME }}
+#            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
+#            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
+#            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
+#            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
+#            MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
+#            SPRING_DATABASE_URL=${{ secrets.SPRING_DATABASE_URL }}
+#            ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}
+#            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
+#            S3_REGION=${{ secrets.S3_REGION }}
+#            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
+#            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
+#            JWT_SECRET=${{ secrets.JWT_SECRET }}
+#            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
+#            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
+#            GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
+#            EOF
+#
+#            echo "[Disk] Before cleanup"
+#            df -h /
+#
+#            docker container prune -f
+#            docker image prune -f
+#            #docker network prune -f
+#
+#            # shared-net 네트워크 생성 (없는 경우에만)
+#            docker network ls | grep shared-net || docker network create shared-net
+#
+#            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
+#              | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
+#
+#            docker pull ${{ secrets.ECR_REGISTRY }}/${{ inputs.module }}:latest
+#
+#            docker compose down ${{ inputs.compose_service }}
+#            docker compose up -d ${{ inputs.compose_service }}
+#
+#            echo "=== Container Status ==="
+#            docker ps -a || true
+#
+#            echo "=== Logs (${{ inputs.compose_service }}) ==="
+#            docker compose logs ${{ inputs.compose_service }} || true
